# -*- coding: utf-8 -*-
"""storygenerator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16pa7y0D_Tenx48N1bK4tAy90uGGIGj9r
"""

print ("Welcome to Story Generator! Give me a few words and I'll write you a story.")
print ("Give me an adjective (a describing word, like 'smelly')")
adj = input()
animal=input('Give me an animal')
print('Give me a place')
place=input()
print("Give me a verb ending in -ing (like 'dancing')")
verb=input()
print("Give me an adverb (a word ending in -ly, like 'badly')")
adverb=input()
print('Give me a food')
food= input()
print(f'''Here is your story:

Yesterday, I was walking near {place} when I suddenly saw
an {adj} {animal}. It was {verb} very {adverb}
and eating {food} at the same time. I have never seen anything
like it in my life. I don't think anyone will believe me.''')